name: Code Styling Enforcement

on:
  pull_request:
    types:
      - synchronize
      - opened
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  linting:
    name: Code Styling
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
      - name: Checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install workflow dependencies
        run: pip install poetry
      - name: Install Project Dependencies
        run: poetry install
      - name: Run flake8
        run: poetry run flake8 .
      - name: Run isort
        run: poetry run isort . --check-only
      - name: Run black
        run: poetry run black . --check
      - run: Run Mypy
        run: poetry run mypy .
